version: "3"

services:
  # Nginx
  nginx:
    restart: always
    build: ./nginx/prod
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    networks:
      - web-network
    volumes:
      - /etc/letsencrypt/live/trade-bot.duckdns.org/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/live/trade-bot.duckdns.org/privkey.pem:/etc/nginx/ssl/privkey.pem

  # Web
  web-db:
    image: postgres:16
    volumes:
        - ./db/web-postgres:/var/lib/postgresql/data/
    ports:
        - 5435:5432
    env_file:
        - .env
    networks:
      - web-network
      
  redis:
    ports:
      - 6380:6379
    volumes:
      - ./db/web-redis:/data
    image: redis:7-alpine
    networks:
      - web-network

  web:
    restart: always
    build: ./web
    command: sh -c "sleep 2 && gunicorn myproject.wsgi:application -w 4 -b 0.0.0.0:8000 --access-logfile - --error-logfile -"
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./web:/app
    depends_on:
      - web-db
      - redis
    networks:
      - web-network
      - telegram-network
      - trading-network

  celery:
    build: ./web
    command: sh -c "celery -A myproject worker --loglevel=info"
    volumes:
      - ./web:/app
    env_file:
      - .env
    depends_on:
        - redis
    networks:
      - web-network

  celery-beat:
    build: ./web
    command: celery -A myproject beat --loglevel=Error
    env_file:
      - .env
    volumes:
      - ./web:/app
    depends_on:
      - celery
    networks:
      - web-network

  # Telegram
  # telegram:
  #   build: ./telegram
  #   env_file:
  #     - .env
  #   restart: always
  #   volumes:
  #     - ./telegram:/app
  #   networks:
  #     - telegram-network
  #   depends_on:
  #     - web

  # Trading
  # trading:
  #   build: ./trading
  #   env_file:
  #     - .env
  #   restart: always
  #   volumes:
  #     - ./trading:/app
  #   networks:
  #     - trading-network
  #   depends_on:
  #     - web
  #   tty: true

networks:
  web-network:
  telegram-network:
  trading-network:
