version: "3"

services:
  # nginx:
  #   restart: always
  #   build: ./nginx/test
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - web
  #   networks:
  #     - trade-bot-network

  db:
    image: postgres:16
    volumes:
        - ./db/postgres:/var/lib/postgresql/data/
    ports:
        - 5435:5432
    env_file:
        - .env
    networks:
      - trade-bot-network
      
  redis:
    ports:
      - 6380:6379
    volumes:
      - ./db/redis:/data
    image: redis:7-alpine
    networks:
      - trade-bot-network

  web:
    restart: always
    build: .
    # command: sh -c "sleep 2 && gunicorn myproject.wsgi:application -w 4 -b 0.0.0.0:8000"
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8001:8000
    env_file:
      - .env
    volumes:
      - ./app:/app
    depends_on:
      - redis
    networks:
      - trade-bot-network

  celery:
    build: .
    command: sh -c "celery -A myproject worker --loglevel=info"
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
        - redis
    networks:
      - trade-bot-network

  celery-beat:
    build: .
    command: celery -A myproject beat --loglevel=Error
    env_file:
      - .env
    volumes:
      - ./app:/app
    depends_on:
      - celery
    networks:
      - trade-bot-network

networks:
  trade-bot-network:
